export type Category = "panaderia" | "dulces" | "pastas";

export interface Product {
  id: string;
  name: string;
  category: Category;
  price: number;
  description: string;
  image: string | null;
  available: boolean;
  badge?: string;
  unit?: string;
}

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "panaderia", label: "Panadería" },
  { id: "dulces", label: "Dulces & Repostería" },
  { id: "pastas", label: "Pastas" },
];

export const PRODUCTS: Product[] = [
  // PANADERÍA
  {
    id: "pan-campo",
    name: "Pan de Campo",
    category: "panaderia",
    price: 9800,
    description: "Hogaza de pan artesanal de 550 g, crocante por fuera y esponjoso por dentro.",
    image: "/productos/pan-de-campo.jpg",
    available: true,
  },
  {
    id: "pan-lomo",
    name: "Pan de Lomo",
    category: "panaderia",
    price: 3900,
    description: "Pan alargado ideal para lomos y sándwiches.",
    image: "/productos/pan-de-lomo.JPG",
    available: true,
  },
  {
    id: "pan-hamburguesa",
    name: "Pan de Hamburguesa",
    category: "panaderia",
    price: 4600,
    description: "Brioche suave y esponjoso, perfecto para burgers.",
    image: "/productos/pan-de-hamburguesa.jpeg",
    available: true,
    badge: "x2 unidades",
  },
  {
    id: "pan-arabe",
    name: "Pan Árabe",
    category: "panaderia",
    price: 4600,
    description: "Finito y flexible, ideal para wraps y falafel.",
    image: "/productos/pan-arabe.jpg",
    available: true,
    badge: "x2 unidades",
  },
  {
    id: "fajitas-xs",
    name: "Fajitas XS",
    category: "panaderia",
    price: 3200,
    description: "Formato pequeño, perfectas para appetizers.",
    image: null,
    available: false,
    badge: "No disponible",
  },
  {
    id: "bollitos",
    name: "Bollitos",
    category: "panaderia",
    price: 5500,
    description: "Bollitos tiernos, ideales para el desayuno o la merienda.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "prepizza",
    name: "Prepizza",
    category: "panaderia",
    price: 4300,
    description: "Base de pizza lista para hornear, crocante y sabrosa.",
    image: "/productos/prepizza.jpeg",
    available: true,
    badge: "x2 unidades",
  },

  // DULCES & REPOSTERÍA
  {
    id: "budin-chocolate",
    name: "Budín de Chocolate",
    category: "dulces",
    price: 4200,
    description: "Porción de 110 g. Húmedo, intenso y con chips de chocolate.",
    image: "/productos/budin-de-chocolate.png",
    available: true,
    badge: "110 g",
  },
  {
    id: "budin-limon",
    name: "Budín de Limón",
    category: "dulces",
    price: 3600,
    description: "Porción de 110 g. Fresco y cítrico, con glasé de limón.",
    image: "/productos/budin-de-limon.jpg",
    available: true,
    badge: "110 g",
  },
  {
    id: "budin-naranja",
    name: "Budín de Naranja",
    category: "dulces",
    price: 3600,
    description: "Porción de 110 g. Esponjoso con sabor a naranja natural.",
    image: "/productos/budin-naranja.jpg",
    available: true,
    badge: "110 g",
  },
  {
    id: "budin-vainilla",
    name: "Budín de Vainilla",
    category: "dulces",
    price: 3300,
    description: "Porción de 110 g. Clásico y suave, perfecto para compartir.",
    image: "/productos/budin-vainilla.jpg",
    available: true,
    badge: "110 g",
  },
  {
    id: "budin-coco",
    name: "Budín de Coco",
    category: "dulces",
    price: 4000,
    description: "Porción de 110 g. Tropical y húmedo, con coco rallado.",
    image: "/productos/budin-coco-y-chips-chocolate.jpg",
    available: true,
    badge: "110 g",
  },
  {
    id: "cookie-lady",
    name: "Cookie Lady Pistacho",
    category: "dulces",
    price: 4300,
    description: "Galleta de 90 g con sabor pistacho.",
    image: null,
    available: true,
    badge: "90 g",
  },
  {
    id: "cookie-vainilla-chips",
    name: "Cookie Vainilla con Chips",
    category: "dulces",
    price: 3900,
    description: "Galleta de 90 g, suave por dentro y con chips de chocolate.",
    image: "/productos/cookie-vainilla-chips-chocolate.jpg",
    available: true,
    badge: "90 g",
  },
  {
    id: "cookie-naranja-choco",
    name: "Cookie Naranja y Chocolate",
    category: "dulces",
    price: 4100,
    description: "Galleta de 90 g. Combinación irresistible de naranja con chocolate amargo.",
    image: "/productos/cookie-naranja-chocolate.png",
    available: true,
    badge: "90 g",
  },
  {
    id: "cookie-caramelo-mani",
    name: "Cookie Caramelo y Maní",
    category: "dulces",
    price: 4200,
    description: "Galleta de 90 g con dulce de leche, caramelo crocante y maní tostado.",
    image: null,
    available: true,
    badge: "90 g",
  },
  {
    id: "cookie-red-velvet",
    name: "Cookie Red Velvet rellena de frutilla",
    category: "dulces",
    price: 4100,
    description: "Galleta de 90 g, red velvet rellena de mermelada de frutilla.",
    image: "/productos/cookie-red-velvet.jpg",
    available: true,
    badge: "90 g",
  },
  {
    id: "alfajor-maizena",
    name: "Alfajor de Maizena",
    category: "dulces",
    price: 6100,
    description: "Clásicos cordobeses, rellenos de dulce de leche y cubiertos de coco.",
    image: "/productos/alfajor-maicena.jpg",
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "rosca-canela",
    name: "Rolls de Canela",
    category: "dulces",
    price: 4900,
    description: "Masa enrollada con azúcar y canela.",
    image: null,
    available: true,
  },

  // PASTAS — actualmente no disponibles
  {
    id: "ravioles-carne",
    name: "Ravioles de Carne Desmechada",
    category: "pastas",
    price: 12000,
    description: "Rellenos de carne desmechada con queso. Tiernos y sabrosos.",
    image: "/productos/ravioles-carne-desmechada-y-queso.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "ravioles-pollo",
    name: "Ravioles de Pollo al Champignon",
    category: "pastas",
    price: 12000,
    description: "Pollo jugoso con salsa de champignon. Una combinación gourmet.",
    image: "/productos/ravioles-pollo-al-champignon.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "ravioles-humita",
    name: "Ravioles de Humita",
    category: "pastas",
    price: 12000,
    description: "Choclo, cebolla y queso. El clásico del norte argentino en cada raviol.",
    image: "/productos/ravioles-humita.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "ravioles-jamon",
    name: "Ravioles de Jamón y Queso",
    category: "pastas",
    price: 12000,
    description: "El clásico de siempre, en versión sin gluten.",
    image: "/productos/ravioles-jamon-y-queso.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "ravioles-boniato",
    name: "Ravioles de Boniato, Queso Azul y Nuez",
    category: "pastas",
    price: 12000,
    description: "Dulce del boniato, picante del azul y textura de nuez.",
    image: "/productos/ravioles-boniato-queso-azul-y-nuez.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "ravioles-caprese",
    name: "Ravioles Caprese",
    category: "pastas",
    price: 12000,
    description: "Mozzarella, tomate y albahaca. El clásico italiano en formato raviol.",
    image: "/productos/ravioles-caprese.jpeg",
    available: false,
    unit: "x12 unidades",
    badge: "No disponible",
  },
  {
    id: "fettuccini",
    name: "Fettuccini",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: "/productos/fetuccinni.jpeg",
    available: false,
    badge: "Próximamente",
  },
  {
    id: "lasagna",
    name: "Lasagna",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
  {
    id: "noquis",
    name: "Ñoquis",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
  {
    id: "spaghetti",
    name: "Spaghetti",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: 0,
  }).format(price);
}
