export type Category = "panaderia" | "dulces" | "pastas";

export interface Product {
  id: string;
  name: string;
  category: Category;
  price: number;
  description: string;
  image: string | null;
  available: boolean;
  badge?: string;
  unit?: string;
}

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "panaderia", label: "Panadería" },
  { id: "dulces", label: "Dulces & Repostería" },
  { id: "pastas", label: "Pastas" },
];

export const PRODUCTS: Product[] = [
  // PANADERÍA
  {
    id: "pan-campo",
    name: "Pan de Campo",
    category: "panaderia",
    price: 4200,
    description: "Pan artesanal de campo, crocante por fuera y esponjoso por dentro.",
    image: null,
    available: true,
  },
  {
    id: "pan-lomo",
    name: "Pan de Lomo",
    category: "panaderia",
    price: 3800,
    description: "Pan alargado ideal para lomos y sándwiches.",
    image: null,
    available: true,
  },
  {
    id: "pan-hamburguesa",
    name: "Pan de Hamburguesa",
    category: "panaderia",
    price: 3600,
    description: "Brioche suave y esponjoso, perfecto para burgers.",
    image: null,
    available: true,
    badge: "x4 unidades",
  },
  {
    id: "pan-arabe",
    name: "Pan Árabe",
    category: "panaderia",
    price: 3200,
    description: "Finito y flexible, ideal para wraps y falafel.",
    image: null,
    available: true,
    badge: "x4 unidades",
  },
  {
    id: "fajitas-xl",
    name: "Fajitas XL",
    category: "panaderia",
    price: 3800,
    description: "Grandes y flexibles para armar tus fajitas favoritas.",
    image: null,
    available: true,
    badge: "x4 unidades",
  },
  {
    id: "fajitas-xs",
    name: "Fajitas XS",
    category: "panaderia",
    price: 3200,
    description: "Formato pequeño, perfectas para appetizers.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "bollitos",
    name: "Bollitos",
    category: "panaderia",
    price: 3400,
    description: "Bollitos tiernos, ideales para el desayuno o la merienda.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "pan-tarro",
    name: "Pan de Tarro",
    category: "panaderia",
    price: 5200,
    description: "Pan de molde esponjoso, cortado en fetas.",
    image: null,
    available: true,
  },

  // DULCES & REPOSTERÍA
  {
    id: "budin-chocolate",
    name: "Budín de Chocolate",
    category: "dulces",
    price: 6500,
    description: "Húmedo, intenso y con chips de chocolate. Irresistible.",
    image: null,
    available: true,
  },
  {
    id: "budin-limon",
    name: "Budín de Limón",
    category: "dulces",
    price: 6500,
    description: "Fresco y cítrico, con glasé de limón encima.",
    image: null,
    available: true,
  },
  {
    id: "budin-naranja",
    name: "Budín de Naranja",
    category: "dulces",
    price: 6500,
    description: "Esponjoso con sabor a naranja natural.",
    image: null,
    available: true,
  },
  {
    id: "budin-vainilla",
    name: "Budín de Vainilla",
    category: "dulces",
    price: 6500,
    description: "Clásico y suave, perfecto para compartir.",
    image: null,
    available: true,
  },
  {
    id: "budin-coco",
    name: "Budín de Coco",
    category: "dulces",
    price: 6500,
    description: "Tropical y húmedo, con coco rallado.",
    image: null,
    available: true,
  },
  {
    id: "cookie-lady",
    name: "Cookie Lady Picardías",
    category: "dulces",
    price: 4200,
    description: "Galletitas redondas con sabor a manteca y vainilla.",
    image: null,
    available: true,
    badge: "x12 unidades",
  },
  {
    id: "cookie-vainilla-chips",
    name: "Cookie Vainilla con Chips",
    category: "dulces",
    price: 4500,
    description: "Suaves por dentro, con chips de chocolate en cada mordida.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "cookie-naranja-choco",
    name: "Cookie Naranja y Chocolate",
    category: "dulces",
    price: 4500,
    description: "Combinación irresistible de naranja con chocolate amargo.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "cookie-caramelo-mani",
    name: "Cookie Caramelo y Maní",
    category: "dulces",
    price: 4500,
    description: "Dulce de leche, caramelo crocante y maní tostado.",
    image: null,
    available: true,
    badge: "x6 unidades",
  },
  {
    id: "cookie-red-velvet",
    name: "Cookie Red Velvet con Nutella",
    category: "dulces",
    price: 5200,
    description: "Red velvet rellena de Nutella. El favorito de la casa.",
    image: null,
    available: true,
    badge: "x4 unidades",
  },
  {
    id: "alfajor-maizena",
    name: "Alfajor de Maizena",
    category: "dulces",
    price: 3800,
    description: "Clásico cordobés, relleno de dulce de leche y cubierto de coco.",
    image: null,
    available: true,
    badge: "x4 unidades",
  },
  {
    id: "rosca-canela",
    name: "Rosca de Canela",
    category: "dulces",
    price: 7200,
    description: "Masa hojaldrada enrollada con azúcar y canela.",
    image: null,
    available: true,
  },
  {
    id: "panettone",
    name: "Panettone",
    category: "dulces",
    price: 9800,
    description: "Pan dulce navideño con frutos secos y chips de chocolate.",
    image: null,
    available: true,
  },
  {
    id: "prepizza",
    name: "Prepizza",
    category: "dulces",
    price: 4800,
    description: "Base de pizza lista para hornear, crocante y sabrosa.",
    image: null,
    available: true,
    badge: "x2 unidades",
  },

  // PASTAS
  {
    id: "ravioles-carne",
    name: "Ravioles de Carne Desmechada",
    category: "pastas",
    price: 12000,
    description: "Rellenos de carne desmechada con queso. Tiernos y sabrosos.",
    image: "/productos/vacio-mozzarella.jpg",
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "ravioles-pollo",
    name: "Ravioles de Pollo al Champignon",
    category: "pastas",
    price: 12000,
    description: "Pollo jugoso con salsa de champignon. Una combinación gourmet.",
    image: "/productos/pollo-verduras.jpg",
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "ravioles-choclo",
    name: "Ravioles de Choclo, Cebolla y Queso",
    category: "pastas",
    price: 12000,
    description: "Sabores del campo argentino en cada raviole.",
    image: null,
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "ravioles-jamon",
    name: "Ravioles de Jamón y Queso",
    category: "pastas",
    price: 12000,
    description: "El clásico de siempre, en versión sin gluten.",
    image: "/productos/jamon-queso.jpg",
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "ravioles-boniato",
    name: "Ravioles de Boniato, Queso Azul y Nuez",
    category: "pastas",
    price: 12000,
    description: "Dulce del boniato, picante del azul y textura de nuez.",
    image: "/productos/boniato-azul-nueces.jpg",
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "ravioles-mozzarella-pesto",
    name: "Ravioles de Mozzarella, Pesto y Tomates",
    category: "pastas",
    price: 12000,
    description: "Mozzarella fundida, pesto de albahaca y tomates caramelizados.",
    image: "/productos/mozzarella-tomate-albahaca.jpg",
    available: true,
    unit: "x12 unidades",
  },
  {
    id: "fettuccini",
    name: "Fettuccini",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
  {
    id: "lasagna",
    name: "Lasagna",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
  {
    id: "noquis",
    name: "Ñoquis",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
  {
    id: "spaghetti",
    name: "Spaghetti",
    category: "pastas",
    price: 0,
    description: "Próximamente disponible.",
    image: null,
    available: false,
    badge: "Próximamente",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: 0,
  }).format(price);
}
